name: Update Wings Image

on:
  workflow_dispatch:
env:
    DAEMON_PROJECT_NAME: pterodactyl-daemon
jobs:
  build_push_wings:
    name: Build and Push Wings Container
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v4

    - name: Read Version
      id: read_version
      run: |
        echo "::set-output name=version::$(grep -Po "DAEMON_VERSION=\K[^ ]+" ./manifest/version.txt)"
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./manifest/images/daemon
        file: ./manifest/images/daemon/Dockerfile
        platforms: linux/arm64
        push: true
        build-args: VERSION=${{ steps.read_version.outputs.version }}
        tags: |
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DAEMON_PROJECT_NAME }}:latest"
          "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DAEMON_PROJECT_NAME }}:${{ steps.read_version.outputs.version }}"
